version: '3.4'

services:
  socially.usermanagment.web:
    image: ${DOCKER_REGISTRY-}sociallyusermanagmentweb
    build:
      context: .
      dockerfile: Socially.UserManagment/src/Socially.UserManagment.Web/Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "5555:8080"
      - "5556:8081"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port for communication
      - "15672:15672" # RabbitMQ management UI port
    restart: always   # Ensure RabbitMQ restarts if it fails  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  socially.contentmanagment.web:
    image: ${DOCKER_REGISTRY-}sociallycontentmanagmentweb
    build:
      context: .
      dockerfile: Socially.ContentManagment/src/Socially.ContentManagment.Web/Dockerfile
    depends_on: 
      - rabbitmq
      - socially.usermanagment.web
    ports:
        - "5557:8080"
        - "5558:8081" 


  socially.messaging.web:
    image: ${DOCKER_REGISTRY-}sociallymessagingweb
    build:
      context: .
      dockerfile: Socially.Messaging/src/Socially.Messaging.Web/Dockerfile
    depends_on: 
      - rabbitmq
      - socially.usermanagment.web
      - socially.contentmanagment.web
    ports:
        - "5559:8080"
        - "5560:8081" 
