version: '3.4'

services:
  socially.usermanagment.web:
    image: ${DOCKER_REGISTRY-}sociallyusermanagmentweb
    build:
      context: .
      dockerfile: Socially.UserManagment/src/Socially.UserManagment.Web/Dockerfile

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ port for communication
      - "15672:15672" # RabbitMQ management UI port
    networks:
      - shared_network
    restart: always   # Ensure RabbitMQ restarts if it fails

networks:
  shared_network:
    driver: bridge