name: UserManagment Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up .NET SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # Specify the version of .NET you are using

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore Socially.UserManagment/tests/Socially.UserManagment.UnitTests/Socially.UserManagment.UnitTests.csproj

      # Build the solution
      - name: Build solution
        run: dotnet build --no-restore Socially.UserManagment/tests/Socially.UserManagment.UnitTests/Socially.UserManagment.UnitTests.csproj

      # Run unit tests
      - name: Run tests
        run: dotnet test --no-build --verbosity normal Socially.UserManagment/tests/Socially.UserManagment.UnitTests/Socially.UserManagment.UnitTests.csproj
